version: '3'
services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "80:8000"

    volumes:
      - /opt/docker/data:/app/data

    environment:
      - SECRET_KEY
      - DEBUG
      - ALLOWED_HOSTS
      - CORS_ORIGIN_WHITELIST
